apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ../../../../../iac-modules/extensions/namespace/v1/
  - ../../../../../iac-modules/extensions/cilium/v1.18.3-v1/  
# patches:
#   - path: values.yaml
#     target:
#       kind: HelmRelease
#       name: prometheus-community