github:
    username: ENC[AES256_GCM,data:q6Jhx6n6ng==,iv:tviuUCjhzy/VaCGLf7blC8G1jzEsmST/YJGqTvE0Czw=,tag:0ixfAlwLD6iu7QP+2i3q0A==,type:str]
    token: ENC[AES256_GCM,data:ns/Hb1I+GBqq+OeU4m68Y/Ii5Pjwve94MgnB9D95GXqOQG1QFqSEEg==,iv:6d8CxavW6mxhpTix1nZZcUX2k6/gNF6F2e0TqQbKgTI=,tag:nKKbVZ5DVvYu+w5U6jJOgw==,type:str]
sops:
    age:
        - recipient: age1ppc0g76en84sppjk7qxljz75wkdvryj87q852pmxuw8k8cwxevqsgpwz3l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSm5EZTZaMllsSnR5djNG
            MXB0eE41Vi9uK3lqTGtOdlFNRS9jdXBxN25FCkoySUNPY3VUKzN6SVJ0VHJnWk1q
            ODhFamJFeXFXOHo2U2tzU0lUdnl6SncKLS0tIE94VHZYMWdTWnJyT0llV1laSXJ5
            dmJJZTl4ZXVKclFUTWZTdHFub0JIVm8KOue1VH0rTMwfWtqTvvHL9vzuvPZrcGXx
            Bc/jkAsVoUAiBmLmat3Tb0GkQC2W+jjH3COU1icfjWNZJNAvbNBvJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T08:07:23Z"
    mac: ENC[AES256_GCM,data:S1y8+17Pgega0TjfMbEYheKQrmerLv1SdgHns8HoFZORhte76cGjnzFvy4O7GXcMu458oYyr3FYPa6poDzQ54qXIQLmDRvvIt7yEd8jZtxAOATqwTXgQKgGBjLsyKyJTpO1JV3XQcLDt5L7rPxwKEWl6CLpMYecrB3sL+IHqeQs=,iv:BKL5ZuPJB8TNx1kaIWYXttn7aPVh6D87a/3HVWgsJCQ=,tag:c8fdqF7uIiFj6vZzzXxsQQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
