github:
    username: ENC[AES256_GCM,data:TqWSKqiB8A==,iv:m/IZxTJTJl5/82z7i/cxnq895d5HO7YX2r0Snv96bj8=,tag:V8y/A8RjLHcSbolBmZDCbQ==,type:str]
    token: ENC[AES256_GCM,data:25ylkue1G+N2J7XxplsEQRJtOPrl784qMmoWSqXQTkAhWw3FJ+7ymg==,iv:BGSjRR0dfYdsdTfxhu79vS5odXb+raetTbqYDlxaqK8=,tag:qq7qcRlMhvrulUROKQorAA==,type:str]
sops:
    age:
        - recipient: age1ppc0g76en84sppjk7qxljz75wkdvryj87q852pmxuw8k8cwxevqsgpwz3l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRE9UV3FFd2VLOHIxZFd6
            d2RjeUlSUG90ZkpkMVBoditSK3FRd1JleFFzClZQQ09ZYXZ5ZkJWMnZrMWU0NjNk
            MHEzbHFQaHZuYnRGZXlKcTRjQk9ONmcKLS0tIG0vRVJxa2dEa0NIRWdJUU1NQ3J5
            WWFPb3FtdThHN3BuSVUrMHJUeXJud1EKSkE4IpaIMzSsZSGyJbTdxC8Vx8ffkTEN
            rI4mmAG4bWWz3xLa0Ulz07hBcAKv67b76MYxqYl87sYQ4wMlArY0KA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T11:23:47Z"
    mac: ENC[AES256_GCM,data:BzCF/kw7YVmzrbVuY8yy70TmlGbb/HH2bmXRNFahAkPPuBKC/8wplXCwIUu3tAXcFIwNZ43RH3NmWhVgIVdt+sXKzW4/TTdlozI/PqsDQUHI/ht71lBVwdIzADhuiqrVIkIw7jvhgD7q/FNv19aCFBPYdWpCDptUT1Ru3qAVDyY=,iv:sWRvb/u2/5GHj5jynr8OWgmb5kgK6q4ezVvBYE+96ik=,tag:ijQdtQzmFMCB2M1Nk3rgwA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
