apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ../../../../../iac-modules/extensions/namespace/v1/
  - ../../../../../iac-modules/extensions/flux-instance/v0.33.0/
# patches:
#   - path: values.yaml
#     target:
#       kind: HelmRelease
#       name: prometheus-community